[WIP] Columbus-5 update
Anchor-Protocol/money-market-contracts pull request #41
Opened 2021-09-05 04:47 UTC by MSNTCS

2021-09-05 04:56 UTC, MSNTCS reviewed
@ezaanm Please resolve conflicts.

2021-09-05 14:00 UTC, YunSuk-Yeo requested changes
Need some changes in raw query

2021-09-06 02:29 UTC, ezaanm commented on contracts/market/src/contract.rs
> +#[cfg_attr(not(feature = "library"), entry_point)]
https://github.com/Anchor-Protocol/money-market-contracts/pull/39

2021-09-06 02:30 UTC, ezaanm commented on contracts/market/src/migration.rs
> +fn read_legacy_config(storage: &dyn Storage) -> StdResult<LegacyConfig> {
https://github.com/Anchor-Protocol/money-market-contracts/pull/39

2021-09-06 02:51 UTC, ezaanm commented on contracts/overseer/src/contract.rs
> +#[cfg_attr(not(feature = "library"), entry_point)]
https://github.com/Anchor-Protocol/money-market-contracts/pull/39

2021-09-06 02:51 UTC, ezaanm commented on packages/moneymarket/src/common.rs
> +pub fn optional_addr_validate(api: &dyn Api, addr: Option<String>) -> StdResult<Option<Addr>> {
nowhere else in this repo

2021-09-10 06:51 UTC, MSNTCS commented
Here is alpha version of `moneymarket` https://crates.io/crates/moneymarket/0.3.0-alpha.1

2021-09-24 10:12 UTC, MSNTCS commented
@ezaanm @YunSuk-Yeo I think we can merge this PR.

2021-09-24 16:18 UTC, ezaanm commented
@MSNTCS @YunSuk-Yeo 
![giphy](https://user-images.githubusercontent.com/22108388/134708045-7132029e-8818-480f-a911-ea79fe226bf8.gif)

2021-09-27 04:36 UTC, YunSuk-Yeo approved these changes
lego

2021-09-27 04:49 UTC, merged