feat: Collect staking rewards directly from custody contract
Anchor-Protocol/money-market-contracts pull request #61
Opened 2022-01-14 00:12 UTC by mandrean

- Collect staking rewards directly from custody contract
- Track total cumulative rewards

2022-01-14 05:10 UTC, alwin-peng commented on contracts/custody_beth/src/contract.rs
> +        ExecuteMsg::WithdrawStakingRewards {} => Err(ContractError::Unauthorized {}),
beth needs the same changes as bluna

2022-01-14 05:10 UTC, alwin-peng commented
besides beth comment, LGTM

2022-01-17 08:21 UTC, MSNTCS requested changes

2022-01-17 09:36 UTC, mandrean commented on contracts/custody_bluna/src/state.rs
> +const KEY_GLOBAL_INDEX: &[u8] = b"global_index";
>Please add these states to the beginning of the file.

I honestly think `package-by-feature` is superior to `package-by-layer`, but sure, can do.

2022-01-17 10:30 UTC, mandrean commented on contracts/custody_bluna/src/state.rs
> +const KEY_USER_REWARDS: &[u8] = b"user_rewards";
I thought about it but noticed we don't even use `cw-plus` anywhere in the repo. Sounds good!

2022-01-17 13:44 UTC, mandrean commented on contracts/custody_beth/src/contract.rs
> +        ExecuteMsg::WithdrawStakingRewards {} => Err(ContractError::Unauthorized {}),
Ah ok. Done 👍

2022-01-17 13:44 UTC, mandrean commented on contracts/custody_bluna/src/state.rs
> +const KEY_GLOBAL_INDEX: &[u8] = b"global_index";
>please also merge KEY_GLOBAL_INDEX and KEY_TOTAL_CUMULATIVE_REWARDS in one single struct.

Done!

2022-01-17 13:44 UTC, mandrean commented on contracts/custody_bluna/src/state.rs
> +pub fn read_total_cumulative_rewards(storage: &dyn Storage) -> Uint256 {
Done!

2022-01-17 13:44 UTC, mandrean commented on contracts/custody_bluna/src/state.rs
> +const KEY_USER_REWARDS: &[u8] = b"user_rewards";
Done!

2022-01-18 15:23 UTC, mandrean commented
![](https://github.trello.services/images/mini-trello-icon.png) [Users collect staking rewards directly from custody contract](https://trello.com/c/dGNGoFIU/23-users-collect-staking-rewards-directly-from-custody-contract)

2022-01-24 17:00 UTC, merged